### Project specific config ###
language: ruby
rvm: 2.3.1
os: linux
install:
  - sudo apt-get install -qq -y dpkg
  - gem install --no-document rubocop

jobs:
  include:
    # Test Atom versions
    - stage: test
      env: ATOM_CHANNEL=stable
      install:
        - gem install --no-document rubocop -v '< 0.52.0'

    - stage: test
      env: ATOM_CHANNEL=stable

    - stage: test
      env: ATOM_CHANNEL=beta

    # Check the commit messages
    - stage: test
      # commitlint requires a current version of Node.js
      language: node_js
      node_js: lts/*
      before_script: skip
      install:
        - npm install
      script:
        - commitlint-travis

    - stage: release
      # Semantic-release requires a current version of Node.js
      language: node_js
      node_js: lts/*
      # Since the deploy needs APM, currently the simplest method is to run
      # build-package.sh, which requires the specs to pass.
      before_deploy:
        - export PATH=${PATH}:${HOME}/atom/usr/bin/
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

before_script:
  - rubocop --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

dist: trusty

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev

stages:
  - test
  - name: release
    if: (NOT type = pull_request) AND branch = master
